# This is a basic workflow to help you get started with Actions

name: Create Repository Dispatch on release

on:
  release:
    types:
      - created
jobs:
  Create Repository Dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: send_repoditory_dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: release-created
        repository: yamazaki-sensei/test-receive-dispatch
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
