# This is a basic workflow to help you get started with Actions

name: Create Repository Dispatch on release

on:
  release:
    types:
      - created
jobs:
  create_repository_dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1.0.0
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        event-type: release-created
        repository: yamazaki-sensei/test-receive-dispatch
        client-payload: '{"released_ref": "${{ github.ref }}", "released_sha": "${{ github.sha }}"}'
